services:
  neo4j-db:
    image:  neo4j:latest
    container_name: "neo4j_Container"

    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/conf/:/conf/'
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt

    environment:
      NEO4J_AUTH: neo4j/abc123
      dbms_connector_bolt_listen__address: neo4j-db:7687
      dbms_connector_bolt_advertised__address: neo4j-db:7687
    healthcheck:
      test: cypher-shell --username neo4j --password abc123 'MATCH (n) RETURN COUNT(n);' # Checks if neo4j server is up and running
      interval: 10s
      timeout: 10s
      retries: 5


  springboot-graphmodel:
    image: usermovie_image
    container_name: "usermovie_Container"
    depends_on:
      neo4j-db:
        condition: service_healthy # Wait for neo4j to be ready
    ports:
      - 8080:8080
#    environment:
#      NEO4J_AUTH: neo4j/abc123

    links:
      - neo4j-db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - 3000:3000